INSERT INTO APP.USERS VALUES (1,'jjaokk@gmail.com','qwe123');

INSERT INTO APP.CATEGORY VALUES ('Mat',1);
INSERT INTO APP.CATEGORY VALUES ('Nöje',1);
INSERT INTO APP.CATEGORY VALUES ('Sparande',1);
INSERT INTO APP.CATEGORY VALUES ('Hyra',1);
INSERT INTO APP.CATEGORY VALUES ('Lön',1);

INSERT INTO APP.TRANSACTIONS VALUES (1,200,CURRENT_TIMESTAMP,'Hemköp',0,'EXPENSE',null,null,'Mat',1);
INSERT INTO APP.TRANSACTIONS VALUES (2,337,CURRENT_TIMESTAMP,'Willys',0,'EXPENSE',null,null,'Mat',1);
INSERT INTO APP.TRANSACTIONS VALUES (3,5200,CURRENT_TIMESTAMP,'Hyra',0,'EXPENSE',null,null,'Hyra',1);
INSERT INTO APP.TRANSACTIONS VALUES (4,11000,CURRENT_TIMESTAMP,'Lön',0,'INCOME',null,null,'Lön',1);
INSERT INTO APP.TRANSACTIONS VALUES (5,2000,CURRENT_TIMESTAMP,'Sparande',0,'SAVINGS',null,null,'Sparande',1);
